[package]
name = "union-find"
version = "0.1.0"
authors = ["chessai <chessai1996@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bencher = "*"
